version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: streamlit
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    deploy:
      resources:
        limits:
          memory: 9216M